# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for PACKAGE_NAME
# TODO: Replace PACKAGE_NAME throughout.
#
# Usage:
#   pyinstaller packaging/PACKAGE_NAME.spec --clean --noconfirm
#
# Environment variables consumed:
#   APP_VERSION  — injected by CI or scripts/build_pyinstaller.sh
#   BUILD_MODE   — "onefile" | "onedir"  (default: onefile)

import os
import sys
from pathlib import Path

ROOT        = Path(SPECPATH).parent          # repo root
SRC         = ROOT / "src" / "PACKAGE_NAME"  # TODO
APP_NAME    = "PACKAGE_NAME"                 # TODO
APP_VERSION = os.environ.get("APP_VERSION", "0.0.0")
BUILD_MODE  = os.environ.get("BUILD_MODE", "onefile")
ONEFILE     = BUILD_MODE == "onefile"

# ── Icon resolution ───────────────────────────────────────────────────────────
def _icon() -> str | None:
    assets = ROOT / "assets"
    if sys.platform == "win32" and (assets / "icon.ico").exists():
        return str(assets / "icon.ico")
    if sys.platform == "darwin" and (assets / "icon.icns").exists():
        return str(assets / "icon.icns")
    if (assets / "icon.png").exists():
        return str(assets / "icon.png")
    return None

# ── Analysis ─────────────────────────────────────────────────────────────────
a = Analysis(
    [str(SRC / "__main__.py")],
    pathex=[str(SRC)],
    binaries=[],
    datas=[
        # Add data files here, e.g.:
        # (str(ROOT / "assets"), "assets"),
    ],
    hiddenimports=[
        # Add hidden imports your app needs, e.g.:
        # "pkg_resources.py2_warn",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "unittest",
        "email",
        "xml",
        "pydoc",
        "doctest",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

# ── EXE / BUNDLE ─────────────────────────────────────────────────────────────
exe_kwargs = dict(
    name=APP_NAME,
    debug=False,
    bootloader_ignore_signals=False,
    strip=sys.platform != "win32",   # strip on Linux/macOS, not Windows
    upx=False,                        # UPX causes false-positive AV; disable
    console=True,                     # set False for GUI-only apps
    icon=_icon(),
    # Windows-only version resource (generated by CI script):
    version="packaging/windows-version.txt" if sys.platform == "win32" and
        (ROOT / "packaging" / "windows-version.txt").exists() else None,
)

if ONEFILE:
    exe = EXE(pyz, a.scripts, a.binaries, a.datas, **exe_kwargs, onefile=True)
else:
    exe = EXE(pyz, a.scripts, [], **exe_kwargs, onefile=False)
    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        name=APP_NAME,
        strip=sys.platform != "win32",
        upx=False,
    )

# ── macOS .app bundle ────────────────────────────────────────────────────────
if sys.platform == "darwin":
    app = BUNDLE(
        exe if ONEFILE else coll,
        name=f"{APP_NAME}.app",
        icon=_icon(),
        bundle_identifier="com.ORGANIZATION.PACKAGE_NAME",  # TODO
        info_plist={
            "CFBundleShortVersionString": APP_VERSION,
            "CFBundleVersion": APP_VERSION,
            "NSHighResolutionCapable": True,
            "NSHumanReadableCopyright": f"Copyright © COMPANY_NAME",  # TODO
            # Entitlements applied separately via codesign --entitlements
        },
    )
